xcode_project: Example/SpecLeaks.xcodeproj
xcode_scheme: SpecLeaks-Example
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X

osx_image: xcode10.2
language: objective-c
# cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --repo-update --project-directory=Example
script: 
- xcodebuild -showsdks
- xcodebuild test -workspace Example/SpecLeaks.xcworkspace -list
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/SpecLeaks.xcworkspace -scheme SpecLeaks-Example -sdk iphonesimulator12.2 -destination 'platform=iOS Simulator,name=iPhone X,OS=12.2' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
